# Numpy : Numerical Python

In [1]:
# Def: Numpy is a open source python library used for numerical operations.
# Numpy array are Homogeneous.
# Numpy is designed in C,C++ and Python.

In [ ]:
# Interview Question:
# What is the differences betwwen python list and Numpy array?
# 1. List is heterogeneous ,numpy  array are Homogeneous.
# 2. Numpy array are faster than python list.
# 3. Numpy array runns in parallel on GPU and TPU.
# 4. Dot operator works faster on numpy array.

# 1.install , upgrade and impoprt numpy and checking its version.

conda install numpy
run the above command in Anaconda prompt.
Numpy already come with Anaconda package, so no need to install.
* Don't use the "pip install numpy" for installing numpy in anaconda environment
* this can create the issues related to versions incompatibility

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

# Creating numpy arrays

In [4]:
# Ex-1: numpy array of integers
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [5]:
# Ex-2: numpy array of float
arr2 = np.array([1.4,2.3,3.5,4.6,5.7])
print(arr2)
print(type(arr2))
print(arr2.dtype)

[1.4 2.3 3.5 4.6 5.7]
<class 'numpy.ndarray'>
float64


In [7]:
# numpy array are Homogeneous
# Ex-3: numpy array of float + integer
arr3 = np.array([1.4,2.3,3.5,4.6,5.7,10,20])
print(arr3)
print(type(arr3))
print(arr1.dtype)

[ 1.4  2.3  3.5  4.6  5.7 10.  20. ]
<class 'numpy.ndarray'>
int32


In [8]:
# Ex-4 : Numpy array of string
arr4 = np.array(["Hello", "World"])
print(arr4)
print(type(arr4))
print(arr4.dtype)

['Hello' 'World']
<class 'numpy.ndarray'>
<U5


In [9]:
arr4 = np.array(["Hello", "World@12345",10,20])
print(arr4)
print(type(arr4))
print(arr4.dtype)
# U: unicode : special symbols are allowed in unicode : strings


['Hello' 'World@12345' '10' '20']
<class 'numpy.ndarray'>
<U11


In [10]:
# Ex-5 : creating 2D Numpy array 
arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5)
print(type(arr5))
print(arr5.dtype)
print(arr5.ndim) # ndim is used to check the dimension of array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
2


In [4]:
# Ex-6 : creating 3D numoy array
arr6 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr6)
print(type(arr6))
print(arr6.dtype)
print(arr6.ndim)  # ndim is used to check the dimension of array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
int32
3


## 22/09/2026

In [5]:
arr6.shape  

(2, 2, 3)

# 3.Special type of numpy array

In [7]:
# Array of Zeros 
arr_zero = np.zeros(5)   #1D
print(arr_zero)

[0. 0. 0. 0. 0.]


In [8]:
arr_zero = np.zeros((2,3))   #2D
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr_zero = np.zeros((2,2,3))   # 3D
print(arr_zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
# Array of ones
arr_ones = np.ones(5)  # 1D
print(arr_ones)

[1. 1. 1. 1. 1.]


In [12]:
arr_ones = np.ones((2,5))  #2D
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
arr_ones = np.ones((2,2,5))   #3D
print(arr_ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
# Iitialize the numpy array with specific value
arr_spe = np.full(5,100)
print(arr_spe)

[100 100 100 100 100]


In [18]:
arr_spe = np.full((2,5),100)    # 2D
print(arr_spe)

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [19]:
arr_spe = np.full((2,2,5),100)     #3D
print(arr_spe)

[[[100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]]]


In [21]:
# Identity matrix is a squared matrix : rows = column
# diagonal values are one and all other zero
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# random package to generate random/synthetic data

In [23]:
# rand() function generate random elements between 0 and 1
np.random.rand(5)  # 1D

array([0.09550932, 0.44273093, 0.11071174, 0.17813039, 0.48498933])

In [26]:
np.random.rand(2,5) # 2D

array([[0.10909476, 0.84885465, 0.68902321, 0.11832925, 0.15883242],
       [0.99694589, 0.53988295, 0.18171445, 0.92629485, 0.04677095]])

In [29]:
np.random.rand(2,2,5) # 3D   how many elements in there 2*2*5 = 20

array([[[0.47062145, 0.94166155, 0.21671041, 0.1677414 , 0.63485421],
        [0.87517523, 0.71327859, 0.04546529, 0.08189053, 0.57714386]],

       [[0.1264686 , 0.91485558, 0.94371348, 0.84064463, 0.38608868],
        [0.20250251, 0.58486229, 0.49617029, 0.41192787, 0.80735682]]])

In [33]:
# uniform() function generate  uniformaly distrubted data
# uniformly distributed means all values have equal probability to get selected
np.random.uniform(low = 1, high = 100, size = 5)

array([36.36695571, 93.83487883, 73.44467011,  9.39278697, 56.83283271])

In [34]:
np.random.uniform(low = 1, high = 100, size = (2,5))

array([[37.77959611, 51.15200396, 15.33698235, 38.84311242, 91.60924369],
       [14.11221775, 45.29587288, 40.47353344, 40.09636917,  8.22179731]])

In [36]:
# random() function just like rand() function
np.random.random((5))

array([0.13181728, 0.26205467, 0.30935445, 0.22870705, 0.60239566])

In [37]:
np.random.random((2,5))

array([[0.39889021, 0.89623488, 0.48541742, 0.74113139, 0.00269935],
       [0.39352434, 0.86155085, 0.55281273, 0.97339761, 0.31477827]])

In [40]:
# randn(): normal distribution function. mean = 0, SD = 1
# 99.7% values will br between -3 to +3
np.random.randn(5)

array([-0.20559413, -1.3427598 ,  0.62401976,  1.51908597, -0.37726408])

In [41]:
np.random.randn(1000)

array([ 1.19447366e+00, -1.24748649e+00, -2.75826061e-01,  1.45537288e-01,
        7.71716567e-01,  2.33952556e-01, -4.94535429e-01,  1.95370604e+00,
        3.58264912e-01, -1.39196783e+00, -6.85254010e-01, -8.57104369e-01,
       -2.70287413e-01,  2.88969480e-01,  6.74742421e-01, -5.88154596e-01,
       -1.10911439e+00, -1.17149277e+00,  4.69213283e-01,  6.81907565e-01,
        7.68896272e-01, -6.15375886e-01, -5.82050268e-01, -4.26563031e-01,
        1.37820487e+00,  2.37156234e+00, -9.19005905e-01, -9.57891917e-01,
       -7.34121455e-01,  7.55711051e-01, -7.30312291e-02, -6.25345784e-01,
       -1.57432609e+00, -9.53311831e-01,  4.57413909e-01,  6.08641725e-01,
       -8.46428766e-01, -1.81949054e+00, -9.19561958e-01,  1.35695580e+00,
       -1.48540040e+00,  6.51687442e-01, -3.58896779e-01, -1.35791626e+00,
       -9.77046714e-01,  1.74183329e+00,  8.28479241e-01, -1.01754455e+00,
        2.11686108e+00,  6.94697627e-01, -4.67866351e-01,  7.00652276e-01,
        1.30240003e+00, -

In [43]:
# normal(): normal distrubted: here mean & Standard Devviation(SD) can be different from 0 and 1
# loc = mean, scale = SD
np.random.normal(loc = 5, scale = 1.2, size = 10)

array([5.48806193, 4.49548586, 4.69469181, 4.71627948, 4.75802568,
       4.52445108, 4.98645235, 4.61058958, 4.9285822 , 2.95090014])

In [46]:
np.random.normal(loc = 5, scale = 1.2, size = (2,5))

array([[7.24394906, 3.97726704, 5.6119437 , 2.41183873, 6.95247465],
       [7.31590589, 6.37825182, 5.09778168, 6.1602527 , 5.60846647]])

In [47]:
# random() VS normal()

In [56]:
# choice() function is used for categorical data
np.random.choice(['Paradise', 'Fauzi', 'Spirit', 'Puspa', 'Bhahubali'],size = 10)

array(['Spirit', 'Bhahubali', 'Bhahubali', 'Puspa', 'Bhahubali',
       'Bhahubali', 'Fauzi', 'Puspa', 'Fauzi', 'Fauzi'], dtype='<U9')

In [57]:
np.random.seed(42)
np.random.choice(['Paradise', 'Fauzi', 'Spirit', 'Puspa', 'Bhahubali'],size = 3)

array(['Puspa', 'Bhahubali', 'Spirit'], dtype='<U9')

In [58]:
np.random.choice(['Paradise', 'Fauzi', 'Spirit', 'Puspa', 'Bhahubali'], p= [0.2,0.05,0.05,0.1,0.6],size = 10)

array(['Bhahubali', 'Bhahubali', 'Bhahubali', 'Paradise', 'Bhahubali',
       'Puspa', 'Paradise', 'Bhahubali', 'Paradise', 'Bhahubali'],
      dtype='<U9')

In [1]:
## Day-3 : [23/09/2026]

## creating  sequences , shuffle, Permutation and linearly seperated data

In [3]:
# arrange() function is used for creating a sequence of elements
# arrange() is just similar  to arrange arange() function

import numpy as np
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [5]:
arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [6]:
# shuffle() : used for shuffle the elements
# shuffle() : perform  implace operaction
# shuffle will modify the original array
arr1 = np.arange(10)
print(arr1)

np.random.shuffle(arr1)
arr1

[0 1 2 3 4 5 6 7 8 9]


array([1, 9, 5, 4, 6, 8, 3, 7, 0, 2])

In [10]:
# permutation(): shuffle elements but returns new shuffled array
# this don't modify the original array
arr1 = np.arange(10)
print(arr1)
arr2 = np.random.permutation(arr1)
arr2


[0 1 2 3 4 5 6 7 8 9]


array([4, 3, 7, 6, 0, 1, 2, 5, 8, 9])

In [11]:
arr1 = np.arange(10)
print(arr1)
arr2 = np.random.permutation(arr1)
print(arr2)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[0 4 3 5 8 9 7 6 1 2]
[0 1 2 3 4 5 6 7 8 9]


In [13]:
# linspace() : linearly spaceed array
# linspace(start,end,number of elements)
arr3 = np.linspace(1, 10, 10)
print(arr3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [15]:
arr3 = np.linspace(1, 10, 4)
print(arr3)

[ 1.  4.  7. 10.]


In [16]:
arr3 = np.linspace(1, 10, 100)
print(arr3)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

# 4. Array shape, Reshape and transpose

In [21]:
south_famous_dresses = np.array([["Lungi", "Dhoti", "Kurti"],["Saree", "Anarkali", "Half Saree"]])
print(south_famous_dresses)
print(south_famous_dresses.shape)

[['Lungi' 'Dhoti' 'Kurti']
 ['Saree' 'Anarkali' 'Half Saree']]
(2, 3)


In [22]:
updated_arr = south_famous_dresses.reshape(3,2)
print(updated_arr)

[['Lungi' 'Dhoti']
 ['Kurti' 'Saree']
 ['Anarkali' 'Half Saree']]


In [23]:
updated_arr = south_famous_dresses.reshape(1,6)  # 2D
print(updated_arr)

[['Lungi' 'Dhoti' 'Kurti' 'Saree' 'Anarkali' 'Half Saree']]


In [26]:
updated_arr = south_famous_dresses.reshape(2,3)
print(updated_arr)

[['Lungi' 'Dhoti' 'Kurti']
 ['Saree' 'Anarkali' 'Half Saree']]


In [27]:
updated_arr = south_famous_dresses.reshape(2,1,3)  # 3D      # 2*1*3 = 6  2braces 1row 3columns
print(updated_arr)

[[['Lungi' 'Dhoti' 'Kurti']]

 [['Saree' 'Anarkali' 'Half Saree']]]


In [28]:
updated_arr = south_famous_dresses.reshape(1,2,1,3) # 4D         # 1*2*1*3 = 6  2braces 1row 3columns
print(updated_arr)

[[[['Lungi' 'Dhoti' 'Kurti']]

  [['Saree' 'Anarkali' 'Half Saree']]]]


In [29]:
# while reshaping no.of elements must be same

In [30]:
# ravel() : used for flatten the array, means convert any array to 1D array
arr4 = south_famous_dresses.ravel()
print(arr4)

['Lungi' 'Dhoti' 'Kurti' 'Saree' 'Anarkali' 'Half Saree']


In [32]:
# transpose : convert Row -> Columns -> Row
print(south_famous_dresses)
print(south_famous_dresses.T)  # T = Transpose

[['Lungi' 'Dhoti' 'Kurti']
 ['Saree' 'Anarkali' 'Half Saree']]
[['Lungi' 'Saree']
 ['Dhoti' 'Anarkali']
 ['Kurti' 'Half Saree']]


# 5.Size and Data type of numpy array

In [39]:
counting_telugu = np.array(["Okati", "Rendu", "Mudu", "Nalgu", "Idu"])
print(counting_telugu)

['Okati' 'Rendu' 'Mudu' 'Nalgu' 'Idu']


In [33]:
counting_telugu = np.array(["Okati", "Rendu", "Mudu", "Nalgu", "Idu"])
print(counting_telugu.size)

5


In [34]:
print(counting_telugu.dtype)

<U5


In [35]:
# astype() : to convert one datatype to another datatype conversion 
arr6 = np.array([10.5, 20.4, 60.6, 40.3]).astype(int)
print(arr6)
print(arr6.dtype)

[10 20 60 40]
int32


In [36]:
arr6 = np.array([10, 20, 60, 40]).astype(float)
print(arr6)
print(arr6.dtype)

[10. 20. 60. 40.]
float64


In [37]:
arr6 = np.array(["10", "20", "60", "40"]).astype(float)
print(arr6)
print(arr6.dtype)

[10. 20. 60. 40.]
float64


In [38]:
arr6 = np.array([True, False, True, True]).astype(int)
print(arr6)
print(arr6.dtype)

[1 0 1 1]
int32


In [43]:
# astype() : to convert one datatype to another datatype conversion 
arr6 = np.array([0, -20, 60.6, 40.3]).astype(bool)
print(arr6)
print(arr6.dtype)

[False  True  True  True]
bool


## 6.Indexing & Slicing & Modification 

In [1]:
import numpy as np
south_sweet = np.array([["Motichoor", "Kalakanda", "Jelabi"],
                        ["Bobbatlu", "Kajji Kaya", "Khaja"]])
print(south_sweet[0][0])

Motichoor


In [2]:
print(south_sweet[1:2])

[['Bobbatlu' 'Kajji Kaya' 'Khaja']]


In [3]:
print(south_sweet[1:2,1])

['Kajji Kaya']


In [4]:
print(south_sweet[0:2,1])

['Kalakanda' 'Kajji Kaya']


In [5]:
print(south_sweet[1,1:3])   #[row,range]

['Kajji Kaya' 'Khaja']


In [6]:
print(south_sweet[0,1:3])   #[row,range]

['Kalakanda' 'Jelabi']


In [7]:
print(south_sweet[0,:])   #[row,range]

['Motichoor' 'Kalakanda' 'Jelabi']


In [8]:
print(south_sweet[1,:])   #[row,range]

['Bobbatlu' 'Kajji Kaya' 'Khaja']


In [9]:
print(south_sweet[0,:2]) 

['Motichoor' 'Kalakanda']


In [10]:
south_sweet = np.array([["Motichoor", "Kalakanda", "Jelabi"],
                        ["Bobbatlu", "Kajji Kaya", "Khaja"]])
print(south_sweet[:,:2]) 

[['Motichoor' 'Kalakanda']
 ['Bobbatlu' 'Kajji Kaya']]


In [11]:
print(south_sweet[-1,-2])   # [ row, range]

Kajji Kaya


In [12]:
print(south_sweet[-1,-1:-2:-1])   # [ row, range]

['Khaja']


### 26/09/2026

## Modifications, insertion & deleition in numpy

In [16]:
import numpy as np

In [19]:
south_sweet = np.array([["Motichoor", "Kalakanda", "Jelabi"],
                         ["Bobbatlu", "Kajji Kaya", "Khaja"]])

# Modification
south_sweet[0,0] = 'Payasam'
print(south_sweet)

[['Payasam' 'Kalakanda' 'Jelabi']
 ['Bobbatlu' 'Kajji Kaya' 'Khaja']]


In [21]:
# updated the complete column
south_sweet[1] = ["Gulab jamoon","kesari","Arisallu"]
print(south_sweet)

[['Payasam' 'Kalakanda' 'Jelabi']
 ['Gulab jamo' 'kesari' 'Arisallu']]


In [28]:
# updated the complete column
# numpy array take fix space to store data
south_sweet[ :, 2] = ['Mysurepak','Doublekamitha']
print(south_sweet)

[['Payasam' 'Kalakanda' 'Mysurepak']
 ['Gulab jamo' 'kesari' 'Doublekami']]


In [31]:
# insert operation : New row
south_sweet = np.insert(south_sweet, 1,['Gajarpak', 'Rasmali', 'Firni'],axis = 0)
print(south_sweet)

[['Payasam' 'Kalakanda' 'Mysurepak']
 ['Gajarpak' 'Rasmali' 'Firni']
 ['Gulab jamo' 'kesari' 'Doublekami']]


In [67]:
# insert operation : New column
south_sweet = np.insert(south_sweet, 2, ['Rasbhari', 'Kheer', 'sabdan Kheer'], axis = 1 )
print(south_sweet)

[['Payasam' 'Kalakanda' 'Rasbhari' 'Mysurepak']
 ['Gajarpak' 'Rasmali' 'Kheer' 'Firni']
 ['Gulab jamo' 'kesari' 'sabdan Khe' 'Doublekami']]


In [68]:
# insert operation :multiple columns
south_sweet = np.insert(south_sweet, 2,
                        [['Khajukatli', 'Ghevar', 'Peda'],['Kajukatli','Ghevar', 'Peda']],
                        axis = 1)
print(south_sweet)
                                                

[['Payasam' 'Kalakanda' 'Khajukatli' 'Kajukatli' 'Rasbhari' 'Mysurepak']
 ['Gajarpak' 'Rasmali' 'Ghevar' 'Ghevar' 'Kheer' 'Firni']
 ['Gulab jamo' 'kesari' 'Peda' 'Peda' 'sabdan Khe' 'Doublekami']]


In [70]:
# delete operation 
south_sweet = np.delete(south_sweet,0, axis = 0)
print(south_sweet)

[['Gajarpak' 'Ghevar' 'Kheer' 'Firni']
 ['Gulab jamo' 'Peda' 'sabdan Khe' 'Doublekami']]


In [72]:
# delete operation : column
south_sweet = np.delete(south_sweet, 2, axis = 1)
print(south_sweet)

[['Gajarpak' 'Ghevar' 'Firni']
 ['Gulab jamo' 'Peda' 'Doublekami']]


In [74]:
# delete operation:column 
south_sweet = np.delete(south_sweet,[1,2], axis = 1)
print(south_sweet)

[['Gajarpak']
 ['Gulab jamo']]


## 7.Mathematical & Statistical operations

In [35]:
sweet_price = np.array([[450, 600, 400], [850, 400, 250]])
print(sweet_price +100)

[[550 700 500]
 [950 500 350]]


In [36]:
print(sweet_price * 2)

[[ 900 1200  800]
 [1700  800  500]]


In [37]:
np.sum(sweet_price)

2950

In [38]:
np.max(sweet_price)

850

In [39]:
np.min(sweet_price)

250

In [40]:
np.mean(sweet_price)

491.6666666666667

In [41]:
np.var(sweet_price)

36180.555555555555

In [42]:
# standard deviation: how much the data far away from the mean
print(np.std(sweet_price))

190.21187017522212


In [51]:
# 100% of the people  are below 850
print(np.percentile(sweet_price, 100))

850.0


In [48]:
# 50% of the people  are below  425
print(np.percentile(sweet_price, 50))

425.0


In [49]:
# 17% of the people  are below  377.5
print(np.percentile(sweet_price, 17))

377.5


In [52]:
sweet_price = np.array([[450, 600, 400], [850, 400, 250]])

In [56]:
# quantile is special type of percentile
np.quantile(sweet_price, 0.50)

425.0

In [59]:
# return the index of largest value
age = [22, 16, 500,14, 8, 20, 90, 200]
np.argmax(age)

2

In [60]:
# return the index of smallest value
age = [22, 16, 500,14, 8, 20, 90, 200]
np.argmin(age)

4

In [63]:
np.sqrt(900)

30.0

In [62]:
pi = 3.142367459245
np.round(pi, 3)

3.142

In [64]:
np.floor(pi)

3.0

In [65]:
np.ceil(pi)

4.0

In [66]:
np.abs(-19)

19