#### Day-1 (07-09-2026)

# PANDAS

# Important list of operation in pandas

# Importing  and installation of pandas


In [4]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

# 1. Data Structure creation (Series (1D array), DataFrame (2D array))  

### Series(1D array)

In [5]:
# Create  Series
ser1 = pd.Series()
print(ser1)               # we use series function

Series([], dtype: object)


In [4]:
# convert  the list to series
list1 = [10, 20, 30, 40, 50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
# convert  the list to series 
# hetroginous elements
# in pandas strings are represented as object
# IMP: In series ,all elements have the same datatype
list1 = [10, 20, 30, 40, 50, "Hello"]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0       10
1       20
2       30
3       40
4       50
5    Hello
dtype: object
<class 'pandas.core.series.Series'>


In [8]:
# Convert tuple to Series
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[2])

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>
30


In [ ]:
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[2])
print(ser2[-2])

# In Pandas Series , direct negative indexing not allowed.

In [11]:
# Set cannot be converted  to pandas series
# Set i unordered and series is ordered, so no conversion
set1 = {10, 20, 30, 40, 50}
ser2 = pd.Series(set1)
print(ser2)

TypeError: 'set' type is unordered

In [12]:
# Convert the numpy array into Series

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [13]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))
ser3 = pd.Series(arr1)
print(arr1, type(ser1))


[10 20 30 40 50] <class 'numpy.ndarray'>
[10 20 30 40 50] <class 'pandas.core.series.Series'>


In [15]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))
ser3 = pd.Series(arr1 , index = ['a' , 'b', 'c', 'd', 'e'])
print(ser3, type(ser3))
print(ser3['a'])

[10 20 30 40 50] <class 'numpy.ndarray'>
a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10


In [32]:
# Update operation on series
ser2[3] = 100000

# insert new value
ser2[5] = 2000
ser2['a'] = 5000
ser2[60] = 7000
ser2[3.4] = 9000
print(ser2)

0          10
2          30
3      100000
4          50
5        2000
a        5000
60       7000
3.4      9000
dtype: int64


In [30]:
# delete elements from  series
ser2 = ser2.drop(1)
ser2

0          10
2          30
3      100000
4          50
5        2000
a        5000
60       7000
3.4      9000
dtype: int64

##### Day: 08/09/2026


# Data Frame is a 2D array , store data in from of matrix. 

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [4]:
# converting list to data frame 
fruits_list = ["AratiPandu", "MamadiPandu", "KamalaPandu", "DrakshaPandu"]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name"])
print(df)

     Fruit Name
0    AratiPandu
1   MamadiPandu
2   KamalaPandu
3  DrakshaPandu


In [5]:
fruits_list = ["AratiPandu", "MamadiPandu", "KamalaPandu", "DrakshaPandu"]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name"])
df

,Fruit Name
0,AratiPandu
1,MamadiPandu
2,KamalaPandu
3,DrakshaPandu


In [6]:
# converting 2D list DataFrame
fruits_list = [["AratiPandu",40], ["MamadiPandu",1000], ["KamalaPandu",10], ["DrakshaPandu",120]]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price"])
df

,Fruit Name,Price
0,AratiPandu,40
1,MamadiPandu,1000
2,KamalaPandu,10
3,DrakshaPandu,120


In [7]:
# created 3 columns dataframe(list of list)
fruits_list = [["AratiPandu",40,100], ["MamadiPandu",1000,200], ["KamalaPandu",10,1000], ["DrakshaPandu",120,100]]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

,Fruit Name,Price,Discount
0,AratiPandu,40,100
1,MamadiPandu,1000,200
2,KamalaPandu,10,1000
3,DrakshaPandu,120,100


In [14]:
# created 3 columns dataframe(list of tuple)
fruits_list = [("AratiPandu",40,100), ("MamadiPandu",1000,200), ("KamalaPandu",10,1000), ("DrakshaPandu",120,-100)]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

,Fruit Name,Price,Discount
0,AratiPandu,40,100
1,MamadiPandu,1000,200
2,KamalaPandu,10,1000
3,DrakshaPandu,120,-100


In [8]:
# creating DataFrame from dictionary
student_data = {
    "Name" : ["Shiva", "Niranjan", "Suresh", "Akash", "Lahari", "Rakesh"],
    "Salary" : [40,50,60,15,25,100],
    "Study_time" : [12,14, 16, 1, 5, 24]
}
df1 = pd.DataFrame(student_data)
df1

,Name,Salary,Study_time
0,Shiva,40,12
1,Niranjan,50,14
2,Suresh,60,16
3,Akash,15,1
4,Lahari,25,5
5,Rakesh,100,24


In [15]:
# convert the set of tuple into DataFrame
fruits_list = [("AratiPandu",40,100), ("MamadiPandu",1000,200), ("KamalaPandu",10,1000), ("DrakshaPandu",120,-100)]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

,Fruit Name,Price,Discount
0,AratiPandu,40,100
1,MamadiPandu,1000,200
2,KamalaPandu,10,1000
3,DrakshaPandu,120,-100


In [18]:
# Creating DataFrame from set of set 
# In set, we cannot store the mutable items
# In set, only immutable items   can be store
fruits_list = {{"AratiPandu", 40, 100} , {"MamadiPandu",1000,200}, {"KamalaPandu",10,1000}, {"DrakshPandu",120,-100}}
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

TypeError: unhashable type: 'set'

In [19]:
# Creating DataFrame from set of list 

fruits_list = {["AratiPandu", 40, 100] , ["MamadiPandu",1000,200], ["KamalaPandu",10,1000], ["DrakshPandu",120,-100]}
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

TypeError: unhashable type: 'list'

## 2.Data input and output (CSV,EXCEL,SQL,JSON)


In [20]:
# importing data from CSV file

import os 
os.getcwd()

'C:\\Users\\gurushankar'

In [7]:
# import a CSV file as DataFrame
df_csv = pd.read_csv("CSV_data.csv")
df_csv

,Name,Age,Profession,Salary,Favorite Quote
0,John,25.0,Software Engineer,80000,Keep calm and code on!
1,Alice,NaN,Doctor,120000,"Trust me, I'm a doctor!"
2,Rocky,NaN,Boxer,50000,Eye of the tiger!
3,Sherlock,40.0,Detective,150000,"It's elementary, my dear Watson."
4,Mr. Bean,50.0,Comedian,10000,Why so serious?
5,Mr. Bean,50.0,Comedian,10000,Why so serious?


In [12]:
# import excel file as a DataFrame
df_excel=pd.read_excel("Excel_data.xlsx")
df_excel


,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5


In [8]:
# export the  data back to csv  and excel file
df_csv.to_excel("Da22_excel.xlsx",index=False)
df_excel.to_csv("Da22_CSV.csv",index=False)

In [ ]:
day-3

In [13]:
df_excel


,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5


In [17]:
# reading and writing inn a sql
import sqlite3
# creating a database if it don't exist
conn = sqlite3.connect("shiva_da22.db")

In [18]:
# creating a table and strating the dataframe data inside it
df_excel.to_sql("prof_table",conn,if_exists='replace')

500

In [19]:
# reading the data from sql table to df
df =pd.read_sql('select * from prof_table',conn)
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5


In [20]:
# impoting data from JSON file 
df_json = pd.read_json('json_data.json')
df_json

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40


In [23]:
# exporting data from dataframe to json file 
df_json.to_json('food_data.json')

## 3. understading the data set (head,tail,dtype,.....)

In [25]:
# view the data with head(),tail() functions
# head(x) function is used to accessing top x records
# head() by default shows the 5 records
df_excel.head(10)

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
5,4,Rocky,56.0,Chef,117920,3
6,4,Rocky,56.0,Chef,117920,11
7,4,Rocky,56.0,Chef,117920,2
8,4,Rocky,56.0,Chef,117920,2
9,4,Rocky,56.0,Chef,117920,3


In [26]:
# tail(x) function is used to accessing bottom x records
# tail() by default shows the 5 records
df_excel.tail(10)

,ID,Name,Age,Profession,salary,Marriage_proposal_count
490,491,John,57.0,Pilot,154180,0
491,492,Emma,34.0,Artist,145412,1
492,493,John,55.0,Artist,57720,2
493,494,Sophia,39.0,Doctor,174500,0
494,495,Rocky,27.0,Doctor,46975,0
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5
499,500,Sherlock,59.0,Software Engineer,194886,28


In [27]:
df_excel.shape

(500, 6)

In [28]:
# shows the single column
df_excel['Name']


0         olivia
1      sophia   
2           jake
3          Rocky
4          Rocky
         ...    
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [29]:
df_excel.Name

0         olivia
1      sophia   
2           jake
3          Rocky
4          Rocky
         ...    
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [30]:
df_excel['Profession']

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...        
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [31]:
df_excel[['Name','Profession']]


,Name,Profession
0,olivia,Teacher
1,sophia,Boxer
2,jake,Scientist
3,Rocky,Chef
4,Rocky,Chef
...,...,...
495,John,Boxer
496,Sherlock,Boxer
497,Sherlock,Detective
498,Olivia,Comedian


In [32]:
# printing multiple columns
df_excel[['Name','Profession','salary']]


,Name,Profession,salary
0,olivia,Teacher,184518
1,sophia,Boxer,119572
2,jake,Scientist,174897
3,Rocky,Chef,117920
4,Rocky,Chef,117920
...,...,...,...
495,John,Boxer,137929
496,Sherlock,Boxer,39870
497,Sherlock,Detective,165951
498,Olivia,Comedian,192618


In [33]:
df_rename=df_excel.rename(columns ={'Name':'peru','Profession':'Vruthi'})
df_rename

,ID,peru,Age,Vruthi,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5


In [34]:

# print all the column names 
df_rename.columns

Index(['ID', 'peru', 'Age', 'Vruthi', 'salary', 'Marriage_proposal_count'], dtype='object')

## creating new column in the dataframe

In [35]:
#  here rank() function is a pandas function
# rank() function is giving rank-1 to minmum salary and higher rank value to higher salary
df_excel['rank'] = df_excel['salary'].rank(ascending =False)
df_excel.sort_values('rank')

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
436,437,Sherlock,52.0,Boxer,199529,3,1.0
65,66,Emma,57.0,Pilot,199317,1,2.0
132,133,Rocky,31.0,Doctor,198978,8,3.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0
474,475,Sophia,30.0,Doctor,198653,1,5.0
...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0
398,399,Rocky,25.0,Scientist,30659,5,498.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0


In [36]:
# droping the column
# axis =1 : delete the column
# axis =0 : delete the row
df_excel=df_excel.drop(['rank'],axis=1)
df_excel

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5
