#### Day-1 (07-09-2026)

# PANDAS

# Important list of operation in pandas

# Importing  and installation of pandas


In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

# 1. Data Structure creation (Series (1D array), DataFrame (2D array))  

### Series(1D array)

In [5]:
# Create  Series
ser1 = pd.Series()
print(ser1)               # we use series function

Series([], dtype: object)


In [4]:
# convert  the list to series
list1 = [10, 20, 30, 40, 50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
# convert  the list to series 
# hetroginous elements
# in pandas strings are represented as object
# IMP: In series ,all elements have the same datatype
list1 = [10, 20, 30, 40, 50, "Hello"]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0       10
1       20
2       30
3       40
4       50
5    Hello
dtype: object
<class 'pandas.core.series.Series'>


In [8]:
# Convert tuple to Series
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [9]:
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[2])

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>
30


In [ ]:
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[2])
print(ser2[-2])

# In Pandas Series , direct negative indexing not allowed.

In [11]:
# Set cannot be converted  to pandas series
# Set i unordered and series is ordered, so no conversion
set1 = {10, 20, 30, 40, 50}
ser2 = pd.Series(set1)
print(ser2)

TypeError: 'set' type is unordered

In [12]:
# Convert the numpy array into Series

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [13]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))
ser3 = pd.Series(arr1)
print(arr1, type(ser1))


[10 20 30 40 50] <class 'numpy.ndarray'>
[10 20 30 40 50] <class 'pandas.core.series.Series'>


In [15]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))
ser3 = pd.Series(arr1 , index = ['a' , 'b', 'c', 'd', 'e'])
print(ser3, type(ser3))
print(ser3['a'])

[10 20 30 40 50] <class 'numpy.ndarray'>
a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10


In [32]:
# Update operation on series
ser2[3] = 100000

# insert new value
ser2[5] = 2000
ser2['a'] = 5000
ser2[60] = 7000
ser2[3.4] = 9000
print(ser2)

0          10
2          30
3      100000
4          50
5        2000
a        5000
60       7000
3.4      9000
dtype: int64


In [30]:
# delete elements from  series
ser2 = ser2.drop(1)
ser2

0          10
2          30
3      100000
4          50
5        2000
a        5000
60       7000
3.4      9000
dtype: int64